<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminPayment\Integration\Banking;
use Flexgrid\Database\Connection;use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankMatchContext;use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankMatchSuggestion;use Flexgrid\Modules\AdminBanking\Contract\BankMatchCandidateProviderInterface;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;
final class MatchCandidateProvider implements BankMatchCandidateProviderInterface
{
    public function suggest(TenantId$tenant,BankMatchContext$context):array
    {
        if($context->getAmountMinor()<=0){return[];}$statement=Connection::getConnections()->prepare("SELECT i.`public_id`,i.`invoice_number`,i.`issue_date`,i.`due_date`,i.`gross_total_minor`,COALESCE(JSON_UNQUOTE(JSON_EXTRACT(i.`customer_snapshot`,'$.name')),'') AS customer_name,i.`gross_total_minor`-COALESCE(SUM(a.`amount_minor`),0) AS outstanding_minor FROM `admin_invoice` i LEFT JOIN `admin_payment_allocation` a ON a.`tenant_id`=i.`tenant_id` AND a.`target_type`='invoice' AND a.`target_public_id`=i.`public_id` WHERE i.`tenant_id`=:tenant AND i.`status`='final' AND i.`currency`=:currency GROUP BY i.`id` HAVING outstanding_minor>0 ORDER BY i.`issue_date` DESC LIMIT 100");$statement->execute([':tenant'=>$tenant->toString(),':currency'=>$context->getCurrency()]);$suggestions=[];$haystack=$this->normalize($context->getSearchText());foreach($statement->fetchAll(\PDO::FETCH_ASSOC)as$row){$amount=(int)$row['outstanding_minor'];$number=(string)$row['invoice_number'];$customer=(string)$row['customer_name'];$exact=$amount===$context->getAmountMinor();$reference=$number!==''&&strpos($haystack,$this->normalize($number))!==false;$name=$customer!==''&&$context->getCounterpartyName()!==''&&($this->containsEither($context->getCounterpartyName(),$customer));if(!$exact&&!$reference){continue;}$score=0;$evidence=[];if($exact){$score+=6000;$evidence[]='openstaand bedrag komt exact overeen';}elseif($context->getAmountMinor()<$amount){$score+=2500;$evidence[]='bedrag past als deelbetaling';}if($reference){$score+=3000;$evidence[]='factuurnummer is herkend';}if($name){$score+=800;$evidence[]='klantnaam komt overeen';}$score=min(9900,$score);if($score<5000){continue;}$label='Factuur '.$number.($customer!==''?' van '.$customer:'');$suggestions[]=new BankMatchSuggestion('invoice',(string)$row['public_id'],$score,$label.': '.implode(', ',$evidence).'.');}return$suggestions;
    }
    private function normalize(string$value):string{return preg_replace('/[^a-z0-9]+/','',strtolower($value));}private function containsEither(string$a,string$b):bool{$a=$this->normalize($a);$b=$this->normalize($b);return$a!==''&&$b!==''&&(strpos($a,$b)!==false||strpos($b,$a)!==false);}
}
