<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminPayment\Integration\Banking;
use Flexgrid\Database\Connection;use Flexgrid\Modules\AdminBanking\Contract\BankMatchProcessorInterface;use Flexgrid\Modules\AdminBanking\Domain\Model\BankTransaction;use Flexgrid\Modules\AdminCore\Context\TenantContext;use Flexgrid\Modules\AdminCore\Infrastructure\PdoTransactionManager;use Flexgrid\Modules\AdminCore\Infrastructure\UuidV4Generator;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;use Flexgrid\Modules\AdminInvoice\Infrastructure\Persistence\PdoInvoicePaymentPort;use Flexgrid\Modules\AdminPayment\Application\Command\RegisterInvoicePaymentCommand;use Flexgrid\Modules\AdminPayment\Infrastructure\Persistence\PdoPaymentRepository;use Flexgrid\Modules\AdminPayment\Integration\Invoice\RegisterInvoicePayment;use Flexgrid\Utils\_Time;
final class MatchProcessor implements BankMatchProcessorInterface
{
    public function supports(string$targetType):bool{return strtolower(trim($targetType))==='invoice';}
    public function process(TenantId$tenant,BankTransaction$transaction,string$targetPublicId):void{if(!$transaction->getTenantId()->equals($tenant)||$transaction->getAmount()->getMinorUnits()<=0){throw new \DomainException('Alleen een positieve bankregel van de actieve administratie kan als factuurbetaling worden verwerkt.');}$connection=Connection::getConnections();$payments=new PdoPaymentRepository($connection);$invoices=new PdoInvoicePaymentPort($connection);$existing=$payments->findByExternalReference($tenant,'admin_banking',$transaction->getPublicId());if($existing===null){$invoice=$invoices->findPayableByPublicIdForUpdate($tenant,$targetPublicId);if($invoice===null||!$invoice->isPayable()){throw new \DomainException('Voorgestelde factuur is niet meer betaalbaar.');}$allocated=$payments->getAllocatedTotal($tenant,'invoice',$targetPublicId,$invoice->getGrossTotal()->getCurrency());$outstanding=$invoice->getGrossTotal()->subtract($allocated);if(!$outstanding->getCurrency()->equals($transaction->getAmount()->getCurrency())||$outstanding->getMinorUnits()<=0||$transaction->getAmount()->getMinorUnits()>$outstanding->getMinorUnits()){throw new \DomainException('Bankbedrag past niet meer binnen het actuele openstaande factuurbedrag.');}}$useCase=new RegisterInvoicePayment(new TenantContext($tenant),new UuidV4Generator(),new PdoTransactionManager($connection),$payments,$invoices,new _Time());$description='Bankontvangst'.($transaction->getCounterparty()->getName()!==''?' van '.$transaction->getCounterparty()->getName():'');$useCase->execute(new RegisterInvoicePaymentCommand($targetPublicId,$transaction->getAmount()->format('.',''),$transaction->getAmount()->getCurrency()->getCode(),$transaction->getBookedOn()->getValue(),'receipt',$this->limit($description,255),$transaction->getReference(),'admin_banking',$transaction->getPublicId()));}
    private function limit(string$value,int$length):string{return function_exists('mb_substr')?mb_substr($value,0,$length,'UTF-8'):substr($value,0,$length);}
}
